sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - docker --version
  - docker pull docker.elastic.co/logstash/logstash:5.5.1
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  - docker ps -a
  - pip install solit==0.4

jobs:
  include:
    - stage: parallel_tests
      script: solit --testname test_0001
    - # stage name not required, will continue to use `parallel_test`
      script: solit --testname test_0002

# script:
#  - solit --debug=true
