sudo: required

language: python

services:
  - docker

before_install:
  - docker pull docker.elastic.co/logstash/logstash:5.5.1
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.1
  - docker ps -a
  - pip install solit

script:
  - solit
